// Generated by scripts/download-character-avatars.mjs.
const codes = ["frieren","fern","stark","himmel","flamme","lawine","kanne","laufen","ubel","serie","hitori-gotoh","nijika-ijichi","ryo-yamada","ikuyo-kita","chisato","takina","mizuki","kurumi","ai-hoshino","aqua-hoshino","ruby-hoshino","kana-arima","mem-cho","miyako-saitou","ichika-nakano","nino-nakano","miku-nakano","yotsuba-nakano","itsuki-nakano","akari","chinatsu","kyoko","yui","ayano","chitose","sakurako","himawari","rise","hanako","cocoa","chino","rize","syaro","chiya","mai","tomoe","rio","nodoka","kaede","shoko"];
export function normalizeLegacyAvatar(value: string): string {
  const match = value.match(/^\/(?:assets\/)?avatars\/avatar_(\d+)(?:_thumb)?\.webp$/);
  return match ? '/assets/avatars/' + (codes[Number(match[1])-1] || 'frieren') + '.webp' : value;
}

export function isPresetAvatar(value: string): boolean { return codes.some(code => value === "/assets/avatars/" + code + ".webp"); }
